name: sahaya
description: Turn your frame design into production-ready frontend code for mobile
  apps and web
publishTo: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
flutter:
  assets:
  - assets/images/
  fonts:
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter-Regular.ttf
    - asset: assets/fonts/Inter-Light.ttf
    - asset: assets/fonts/Inter-Thin.ttf
    - asset: assets/fonts/Inter-ExtraLight.ttf
    - asset: assets/fonts/Inter-SemiBold.ttf
    - asset: assets/fonts/Inter-Medium.ttf
    - asset: assets/fonts/Inter-Bold.ttf
    - asset: assets/fonts/Inter-ExtraBold.ttf
    - asset: assets/fonts/Inter-Black.ttf
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
